"use client";
import React, { useRef } from "react";
import { useRouter } from "next/navigation";
import { CreateCategoryData } from "@/lib/types/category";
import { useCreateCategory, useNotification, useForm } from "@/lib/hooks";
import { TextInput, Textarea } from "@/app/Components/Form";
import { Button, Page, Title, Text, Icon } from "@/app/Components/Common";
import { generateSlug } from "@/lib/utils/dataCleaning";
import { getErrorMessage } from "@/lib/utils/errorHandling";

const AddCategory = () => {
  const router = useRouter();
  const createCategoryMutation = useCreateCategory();
  const { showSuccess, showError } = useNotification();
  const slugManuallyEditedRef = useRef(false);

  const form = useForm<CreateCategoryData>({
    initialValues: {
      name: "",
      slug: "",
      description: "",
    },
    validate: (values) => {
      const errors: Record<string, string> = {};

      if (!values.name) {
        errors.name = "Category name is required";
      }

      if (!values.slug) {
        errors.slug = "Slug is required";
      } else if (!/^[a-z0-9-]+$/.test(values.slug)) {
        errors.slug =
          "Slug can only contain lowercase letters, numbers, and hyphens";
      }

      return errors;
    },
    validateOnChange: true,
    validateOnBlur: true,
  });

  // Auto-generate slug from name (only if not manually edited)
  React.useEffect(() => {
    if (form.values.name && !slugManuallyEditedRef.current) {
      const generatedSlug = generateSlug(form.values.name);
      form.setFieldValue("slug", generatedSlug);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [form.values.name]);

  const handleSubmit = form.handleSubmit(async (values) => {
    try {
      await createCategoryMutation.mutateAsync(values);
      showSuccess("Category created successfully!");
      router.push("/admin/categories");
    } catch (error: unknown) {
      showError(getErrorMessage(error, "Failed to create category"));
    }
  });

  return (
    <Page
      title="Add Category"
      description="Create a new category for tours and blogs"
      headerActions={
        <Button variant="outline" onClick={() => router.back()} leftIcon={<Icon name="arrow-left" />}>
          Back
        </Button>
      }
    >
      <div className="form-container">
        <form onSubmit={handleSubmit} className="tour-form">
          <div className="form-section">
            <div className="section-header">
              <Title order={3}>
                <Icon name="folder" /> Category Information
              </Title>
              <Text className="section-description" color="dimmed">
                Provide the basic details for this category. Categories help
                organize tours and blogs.
              </Text>
            </div>
            <div className="form-grid">
              <div className="form-group">
                <TextInput
                  label="Category Name"
                  placeholder="e.g., Adventure Tours"
                  {...form.getFieldProps("name")}
                  required
                  description="The display name for this category"
                />
              </div>

              <div className="form-group">
                <TextInput
                  label="Slug"
                  placeholder="e.g., adventure-tours"
                  value={form.values.slug}
                  error={form.errors.slug}
                  onBlur={() => {
                    form.setFieldTouched("slug", true);
                    // Mark as manually edited if user changes it differently from auto-generated
                    const autoGenerated = generateSlug(form.values.name);
                    if (form.values.slug !== autoGenerated) {
                      slugManuallyEditedRef.current = true;
                    }
                  }}
                  onChange={(value) => {
                    form.setFieldValue("slug", value);
                    // Mark as manually edited if user changes it differently from auto-generated
                    // Use a timeout to ensure form.values.name is up to date
                    setTimeout(() => {
                      const autoGenerated = generateSlug(form.values.name);
                      if (value !== autoGenerated) {
                        slugManuallyEditedRef.current = true;
                      }
                    }, 0);
                  }}
                  required
                  description="URL-friendly version of the name (auto-generated from name)"
                />
              </div>
            </div>

            <div className="form-group" style={{ marginTop: "1.5rem" }}>
              <Textarea
                label="Description"
                placeholder="Optional description for this category"
                {...form.getFieldProps("description")}
                rows={4}
                description="Optional description that helps identify this category"
              />
            </div>
          </div>

          <div className="form-actions">
            <div className="actions-container">
              <Button
                color="secondary"
                leftIcon={<Icon name="arrow-left" />}
                onClick={() => router.back()}
                type="button"
              >
                Cancel
              </Button>
              <Button
                type="submit"
                loading={createCategoryMutation.isPending}
                leftIcon={
                  !createCategoryMutation.isPending ? (
                    <Icon name="check-lg" />
                  ) : undefined
                }
                disabled={
                  !form.values.name ||
                  !form.values.slug ||
                  !!form.errors.name ||
                  !!form.errors.slug ||
                  createCategoryMutation.isPending
                }
              >
                {createCategoryMutation.isPending
                  ? "Creating..."
                  : "Create Category"}
              </Button>
            </div>
          </div>
        </form>
      </div>
    </Page>
  );
};

export default AddCategory;
